#! /bin/bash
#### AUTOSTART ####
sxhkd &
picom --experimental-backends &
nitrogen --restore &
~/.config/polybar/launch.sh &
~/Startup/pywal.sh &
~/Startup/nvidia.sh &
sh ~/Startup/spotify.sh &

#### MONITORS ####
bspc monitor DP-4 -d 1 2 3 4 5 6
bspc monitor DP-3 -d 9 10
bspc monitor HDMI-0 -d 7 8

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  5
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                5
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#0B090F"
bspc config active_border_color	          "#0B090F"
bspc config focused_border_color	      "#0B090F"
bspc config presel_feedback_color	      "#0B090F"
bspc config urgent_border_color 	      "#0B090F"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-5)

bspc rule -a st-256color monitor='DP-4' desktop='2'
bspc rule -a ranger monitor='DP-4' desktop='3'
bspc rule -a Thunar monitor='DP-4' desktop='3'
bspc rule -a code-oss monitor='DP-4' desktop='4'
bspc rule -a Chromium monitor='DP-4' desktop='1'
bspc rule -a Google-chrome monitor='DP-4' desktop='6'
bspc rule -a "" monitor='HDMI-0' desktop='7'
bspc rule -a discord monitor='HDMI-0' desktop='7'
bspc rule -a Screenkey manage=off
